CREATE TABLE IF NOT EXISTS flags (
	id          INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	key         TEXT NOT NULL,
	name        TEXT NOT NULL,
	description TEXT,
	is_on       BOOLEAN NOT NULL DEFAULT FALSE,
	created_at  TIMESTAMPTZ NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc'),
	updated_at  TIMESTAMPTZ NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc')
)